services:
  - type: web
    name: jj-kitchenette
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    envVars:
      - key: APP_URL
        value: https://jj-kitchenette.onrender.com
      - key: APP_TIMEZONE
        value: Asia/Manila
      - key: APP_SESSION_LIFETIME
        value: 28800
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_SSL_CA
        sync: false
      - key: DB_SSL_CA_CONTENT
        sync: false
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_EMAIL
        sync: false
      - key: MAIL_FROM_NAME
        value: J&J's Kitchenette
